name: topic
on:
  push:
    branches-ignore:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.5', '3.8']

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1.1.1
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install tox
      - run: tox -e py -e cov -e codecov -- -vv
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
